name: CHECK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install shellspec
        run: |
          cd ~
          wget https://github.com/shellspec/shellspec/releases/download/0.28.1/shellspec-dist.tar.gz
          tar -xzf shellspec-dist.tar.gz
          ln -s $(pwd)/shellspec/shellspec /usr/local/bin/shellspec
          ls -l /usr/local/bin/shellspec

      - name: Checkout the repository
        uses: actions/checkout@v3

      - run: shellspec

  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Checkout an example gradle project
        uses: actions/checkout@v3
        with:
          repository: 'unaguna/gradle-example'
          path: 'gradle-example'

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build
        run: ./build.sh

      - name: Run collect-tests.sh
        run: |
          cd build/release
          tar -xzf $(ls -1 | head -n 1)
          ./collect-tests.sh -d result $GITHUB_WORKSPACE/gradle-example
